var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/lessons/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__49dbbe4f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/_14fcc979._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3cacb911._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e17d8479._.js")
R.c("server/chunks/ssr/node_modules_next_dist_a6fcb974._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_layout_tsx_271801d7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_dashboard_layout_tsx_12b56d5a._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_lessons_[slug]_page_actions_defb759a.js")
R.m(96785)
module.exports=R.m(96785).exports
