// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/auth/callback" | "/dashboard" | "/dashboard/lessons" | "/dashboard/lessons/[slug]" | "/dashboard/subscription" | "/dev/lessons" | "/login" | "/pricing" | "/subscription-expired" | "/welcome"
type AppRouteHandlerRoutes = "/api/auth/ensure-user" | "/api/create-checkout-session" | "/api/dashboard/lessons" | "/api/dev/lessons" | "/api/dev/lessons/[id]" | "/api/dev/lessons/recompact" | "/api/dev/lessons/reorder" | "/api/dev/modules" | "/api/dev/modules/[id]" | "/api/webhooks/stripe"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = "/" | "/designsystem"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/ensure-user": {}
  "/api/create-checkout-session": {}
  "/api/dashboard/lessons": {}
  "/api/dev/lessons": {}
  "/api/dev/lessons/[id]": { "id": string; }
  "/api/dev/lessons/recompact": {}
  "/api/dev/lessons/reorder": {}
  "/api/dev/modules": {}
  "/api/dev/modules/[id]": { "id": string; }
  "/api/webhooks/stripe": {}
  "/auth/callback": {}
  "/dashboard": {}
  "/dashboard/lessons": {}
  "/dashboard/lessons/[slug]": { "slug": string; }
  "/dashboard/subscription": {}
  "/designsystem": {}
  "/dev/lessons": {}
  "/login": {}
  "/pricing": {}
  "/subscription-expired": {}
  "/welcome": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
