var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/lessons/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__3c830abb._.js")
R.c("server/chunks/ssr/_9e699131._.js")
R.c("server/chunks/ssr/node_modules_next_dist_28d20d65._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3cacb911._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e17d8479._.js")
R.c("server/chunks/ssr/node_modules_next_dist_a6fcb974._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_layout_tsx_271801d7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_dashboard_layout_tsx_12b56d5a._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_lessons_page_actions_b00fc1d4.js")
R.m(29643)
module.exports=R.m(29643).exports
